DROP TABLE IF EXISTS QUYDINH;
DROP TABLE IF EXISTS PHIEU;
DROP TABLE IF EXISTS UYQUYEN;
DROP TABLE IF EXISTS SOTIETKIEM;

DROP TABLE IF EXISTS LOAIKYHAN;
DROP TABLE IF EXISTS KHACHHANG;

ALTER TABLE CHINHANH DROP CONSTRAINT FK_NVQUANLY;
DROP TABLE IF EXISTS NHANVIEN;
DROP TABLE IF EXISTS GIOLAMVIEC;
DROP TABLE IF EXISTS CHINHANH;

DROP TABLE IF EXISTS BAOCAONGAY;
DROP TABLE IF EXISTS BAOCAOTHANG;