DROP TABLE IF EXISTS QUYDINH;
DROP TABLE IF EXISTS PHIEURUT;
DROP TABLE IF EXISTS PHIEUGUI;
DROP TABLE IF EXISTS SOTIETKIEM;

DROP TABLE IF EXISTS LOAIKYHAN;
DROP TABLE IF EXISTS KHACHHANG;

DROP TABLE IF EXISTS BAOCAONGAY;
DROP TABLE IF EXISTS BAOCAOTHANG;