DROP TABLE IF EXISTS DEBUG;
CREATE TABLE DEBUG
(
    LineNumber INT,
    Message TEXT
);

SELECT * FROM DEBUG;

DROP PROCEDURE  IF EXISTS StartDebug;
DELIMITER $$
CREATE PROCEDURE  StartDebug()
BEGIN
   DELETE FROM DEBUG;
END;
$$
DELIMITER  ;

DROP PROCEDURE IF EXISTS MarkLine;
DELIMITER $$
CREATE PROCEDURE MarkLine(IN LineNumber INT, IN Message TEXT)
BEGIN
    INSERT INTO DEBUG VALUES(LineNumber, Message);
END;
$$
DELIMITER ;

DROP PROCEDURE IF EXISTS Print;
DELIMITER $$
CREATE PROCEDURE  Print(message TEXT) DETERMINISTIC
BEGIN
    SET @message = message;
    PREPARE Stmt FROM 'SELECT ?';
    EXECUTE Stmt USING @message;
    DEALLOCATE PREPARE Stmt;
END;
$$
DELIMITER ;